### ISSUE TITLE
Could you please provide me the download url of the Corpus and some converted samples? 

### ISSUE THREAD

**Issue by zhaoxy0303** [KunZhou9646/Speaker-independent-emotional-voice-conversion-based-on-conditional-VAW-GAN-and-CWT#3]
Hi，I‘m interested in your work. But I failed to find the whole corpus which mentioned in your paper.
And could you please show some samples?

**Comment by KunZhou9646** [comment]
Hi, the link to the sample page is in our Interspeech paper. You may need to check out our paper.
