### ISSUE TITLE
ensorflow.python.framework.errors_impl.InvalidArgumentError: indices[3] = 151 is not in [0, 10)

### ISSUE THREAD

**Issue by c1a1o1** [KunZhou9646/Speaker-independent-emotional-voice-conversion-based-on-conditional-VAW-GAN-and-CWT#4]
ensorflow.python.framework.errors_impl.InvalidArgumentError: indices[3] = 151 is not in [0, 10)
	 [[{{node Generator_3/embedding_lookup_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\supervisor.py", line 1004, in managed_session
    yield sess
  File "F:\work\Singing-Voice-Conversion-with-conditional-VAW-GAN-master\codes\trainer\vawgan.py", line 106, in train
    results = sess.run(fetches, feed_dict=feed_dict)
  File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py",

**Comment by zhaoxy0303** [comment]
> ensorflow.python.framework.errors_impl.InvalidArgumentError: indices[3] = 151 is not in [0, 10)
> [[{{node Generator_3/embedding_lookup_1}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\training\supervisor.py", line 1004, in managed_session
> yield sess
> File "F:\work\Singing-Voice-Conversion-with-conditional-VAW-GAN-master\codes\trainer\vawgan.py", line 106, in train
> results = sess.run(fetches, feed_dict=feed_dict)
> File "F:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py",

Hi,could you please tell me how you solve this problem?

**Comment by giymen** [comment]
Same error for me. I would be glad to hear your solutions..

**Comment by giymen** [comment]
> Same error for me. I would be glad to hear your solutions..

It seems we need to use cudnn/7.0.5/cuda-9.1 for tensorflow 1.5.0. This solved my problem.
